[package]
name = "scarlet-driver-nvidia-gm20b"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"

[dependencies]
maxwell-image-layout = { path = "../../../shared/maxwell-image-layout" }
maxwell-program-wire = { path = "../../../shared/maxwell-program-wire" }

[target.'cfg(target_os = "none")'.dependencies]
scarlet = { git = "https://github.com/petitstrawberry/Scarlet", rev = "cfe8b57bca7d3407e108c3cdf43e0a9fd7dac030", default-features = false, features = ["network"] }
scarlet-driver-tegra210 = { path = "../../soc/tegra210" }
fdt = "0.1.5"
maxwell-shader-pack = { path = "../../../shared/maxwell-shader-pack" }
maxwell-submit-wire = { path = "../../../shared/maxwell-submit-wire" }
