[package]
name = "scarlet-driver-nvidia-gm20b"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"

[dependencies]
maxwell-image-layout = { path = "../../../shared/maxwell-image-layout" }
maxwell-program-wire = { path = "../../../shared/maxwell-program-wire" }

[target.'cfg(target_os = "none")'.dependencies]
scarlet = { git = "https://github.com/petitstrawberry/Scarlet", rev = "388e95b36fc929751220e4aaa2a1f47e0306b00c", default-features = false, features = ["network"] }
scarlet-driver-tegra210 = { path = "../../soc/tegra210" }
fdt = "0.1.5"
maxwell-shader-pack = { path = "../../../shared/maxwell-shader-pack" }
maxwell-submit-wire = { path = "../../../shared/maxwell-submit-wire" }
