[package]
name = "scarlet-driver-tegra210-se-rng"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"

[target.'cfg(target_os = "none")'.dependencies]
scarlet = { git = "https://github.com/petitstrawberry/Scarlet", rev = "73e761b39ef45b0c2048b0f98b1e3700c030d3e2", default-features = false, features = ["network"] }
scarlet-driver-tegra210 = { path = "../../soc/tegra210" }
