[package]
name = "scarlet-driver-tegra210-se-rng"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"

[target.'cfg(target_os = "none")'.dependencies]
scarlet = { git = "https://github.com/petitstrawberry/Scarlet", rev = "388e95b36fc929751220e4aaa2a1f47e0306b00c", default-features = false, features = ["network"] }
scarlet-driver-tegra210 = { path = "../../soc/tegra210" }
