[package]
name = "scarlet-driver-joycon"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"

[target.'cfg(target_os = "none")'.dependencies]
scarlet = { git = "https://github.com/petitstrawberry/Scarlet", rev = "07fefb250020fa72952cca519e554f20c7b5f210", default-features = false, features = ["network"] }
scarlet-driver-tegra210 = { path = "../../soc/tegra210" }
