[package]
name = "scarlet-driver-tegra210-audio"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"

[target.'cfg(target_os = "none")'.dependencies]
scarlet = { git = "https://github.com/petitstrawberry/Scarlet", rev = "4a3d0f34273e11b57345ce06e21ee4420c910043", default-features = false, features = ["network"] }
scarlet-driver-tegra210 = { path = "../../soc/tegra210" }
