//! Bounded tracked submissions with immutable per-submission upload storage.

use alloc::{sync::Arc, vec::Vec};
use gpu_raw::{GPU_ABI_VERSION, GPU_RESULT_SUCCESS, GpuQueue};
use sgfx_codegen_maxwell as codegen;
use sgfx_core::backend::SubmitError;

use crate::dispatch::Chunk;
use crate::execute::validate_fixed_command_subset;
use crate::preparation::{
    PreparedChunk, UPLOAD_ARENA_BYTES, prepare_chunk, split_async_operations,
    split_submission_operations,
};
use crate::resource::{ContextResources, RawBuffer, RawImage};
use crate::scheduler::AdmissionError;
use crate::wire::BoundObject;
use crate::{ContextInner, IrSubmitError, Submission, UnsupportedIrFeature, ir, wire};

/// Four native chunks can use disjoint staging simultaneously; an arbitrarily
/// longer logical stream reuses them after their native fences retire.
const UPLOAD_ARENAS: usize = 4;
const MAX_LOGICAL_BYTES: usize = 64 * 1024 * 1024;

pub(crate) struct UploadArena {
    pub(crate) buffer: RawBuffer,
    pub(crate) completion: std::sync::Mutex<Option<Arc<gpu_raw::GpuCompletion>>>,
}

/// Each physical owner retains both the capability and its context attachment.
/// Keeping these snapshots in queued jobs prevents session Drop from revoking
/// authority needed by a native chunk which has not reached the kernel yet.
pub(crate) struct RetainedResources {
    _images: Vec<Arc<RawImage>>,
    _buffers: Vec<Arc<RawBuffer>>,
}

pub(crate) struct DispatchOwner {
    pub(crate) queue: Arc<GpuQueue>,
    pub(crate) _resources: Arc<RetainedResources>,
}

impl ContextResources {
    pub(crate) fn drain_async(&self) -> Result<(), IrSubmitError> {
        self.context.dispatcher.wait_idle()?;
        Ok(())
    }

    fn prepare_upload_arenas(&mut self) -> Result<(), IrSubmitError> {
        self.async_arenas
            .try_reserve_exact(UPLOAD_ARENAS.saturating_sub(self.async_arenas.len()))
            .map_err(|_| IrSubmitError::OutOfMemory)?;
        while self.async_arenas.len() < UPLOAD_ARENAS {
            let buffer = RawBuffer::create(&self.context, UPLOAD_ARENA_BYTES)?;
            self.async_arenas.push(Arc::new(UploadArena {
                buffer,
                completion: std::sync::Mutex::new(None),
            }));
        }
        Ok(())
    }

    pub(crate) fn submit_async<'r, 'data>(
        &mut self,
        context: &ContextInner,
        queue: &Arc<GpuQueue>,
        commands: &ir::CommandBuffer<'r, 'data>,
    ) -> Result<Submission, SubmitError<IrSubmitError, Submission>> {
        validate_fixed_command_subset(commands).map_err(SubmitError::Rejected)?;
        if context.raw.as_handle().as_raw() != self.context_id() {
            return Err(SubmitError::Rejected(IrSubmitError::ContextMismatch));
        }
        if !core::ptr::eq(commands.resources(), self.resources.as_ref()) {
            return Err(SubmitError::Rejected(IrSubmitError::ResourceTableMismatch));
        }
        let limits = queue
            .query_async()
            .map_err(|_| SubmitError::Rejected(IrSubmitError::AsyncUnsupported))?;
        if limits.abi_version != GPU_ABI_VERSION
            || limits.result != GPU_RESULT_SUCCESS
            || limits.reserved != 0
            || limits.reserved2 != 0
            || limits.max_pending_submissions == 0
            || limits.max_opaque_command_size == 0
        {
            return Err(SubmitError::Rejected(IrSubmitError::AsyncUnsupported));
        }
        // Materialize every logical resource and validate/compile every chunk
        // before accepting work. Borrowed uploads become owned generated bytes.
        let (prepared, external_bindings) = self
            .prepare_async(context, commands, limits.max_opaque_command_size as usize)
            .map_err(SubmitError::Rejected)?;
        self.prepare_upload_arenas()
            .map_err(SubmitError::Rejected)?;
        let mut chunks = Vec::new();
        chunks
            .try_reserve_exact(prepared.len().max(1))
            .map_err(|_| SubmitError::Rejected(IrSubmitError::OutOfMemory))?;
        for (index, chunk) in prepared.into_iter().enumerate() {
            let arena = Arc::clone(&self.async_arenas[index % UPLOAD_ARENAS]);
            let mut bindings = Vec::new();
            bindings
                .try_reserve_exact(external_bindings.len() + chunk.placements.len())
                .map_err(|_| SubmitError::Rejected(IrSubmitError::OutOfMemory))?;
            bindings.extend_from_slice(&external_bindings);
            for &(id, offset, size) in &chunk.placements {
                bindings.push(BoundObject {
                    object: codegen::ObjectRef::Generated(id),
                    attachment_token: arena.buffer.attachment_token,
                    allocation_offset: offset,
                    size,
                });
            }
            let commands =
                wire::encode(&chunk.compiled, &bindings).map_err(SubmitError::Rejected)?;
            let mut uploads = Vec::new();
            uploads
                .try_reserve_exact(chunk.placements.len())
                .map_err(|_| SubmitError::Rejected(IrSubmitError::OutOfMemory))?;
            for (generated, (_, offset, _)) in chunk
                .compiled
                .generated_objects
                .into_iter()
                .zip(chunk.placements)
            {
                uploads.push((offset, generated.bytes));
            }
            chunks.push(Chunk {
                commands,
                arena,
                uploads,
            });
        }
        if chunks.is_empty() {
            chunks.push(Chunk {
                commands: Vec::new(),
                arena: Arc::clone(&self.async_arenas[0]),
                uploads: Vec::new(),
            });
        }
        let mut images = Vec::new();
        let mut buffers = Vec::new();
        images
            .try_reserve_exact(self.images.len())
            .map_err(|_| SubmitError::Rejected(IrSubmitError::OutOfMemory))?;
        buffers
            .try_reserve_exact(self.buffers.len())
            .map_err(|_| SubmitError::Rejected(IrSubmitError::OutOfMemory))?;
        images.extend(self.images.iter().flatten().cloned());
        buffers.extend(self.buffers.iter().flatten().cloned());
        let owner = Arc::new(DispatchOwner {
            queue: Arc::clone(queue),
            _resources: Arc::new(RetainedResources {
                _images: images,
                _buffers: buffers,
            }),
        });
        let dispatcher = &self.context.dispatcher;
        match dispatcher.enqueue(owner, chunks) {
            Ok(signal) => Ok(Submission::new(signal)),
            Err(AdmissionError::Busy) => Err(SubmitError::Busy),
            Err(AdmissionError::TooLarge) => {
                Err(SubmitError::Rejected(IrSubmitError::SubmissionTooLarge))
            }
            Err(AdmissionError::OutOfMemory) => {
                Err(SubmitError::Rejected(IrSubmitError::OutOfMemory))
            }
            Err(AdmissionError::Failed(error)) => Err(SubmitError::Rejected(error.into())),
        }
    }

    fn prepare_async<'r, 'data>(
        &mut self,
        context: &ContextInner,
        commands: &ir::CommandBuffer<'r, 'data>,
        native_limit: usize,
    ) -> Result<(Vec<PreparedChunk>, Vec<BoundObject>), IrSubmitError> {
        let mut resources = Vec::new();
        let mut pipelines = Vec::new();
        let mut operations = Vec::new();
        let mut external_bindings = Vec::new();
        operations
            .try_reserve(commands.commands().len())
            .map_err(|_| IrSubmitError::OutOfMemory)?;
        for command in commands.commands() {
            match command {
                ir::Command::WriteBuffer {
                    buffer,
                    offset,
                    data,
                } => {
                    let destination =
                        self.ensure_buffer(*buffer, &mut resources, &mut external_bindings)?;
                    operations.push(codegen::Operation::WriteBuffer {
                        destination,
                        offset: *offset,
                        data,
                    });
                }
                ir::Command::WriteTexture { texture, write } => {
                    let destination =
                        self.ensure_image(*texture, &mut resources, &mut external_bindings)?;
                    operations.push(codegen::Operation::WriteTexture {
                        destination,
                        area: write.destination(),
                        bytes_per_row: write.bytes_per_row(),
                        data: write.data(),
                    });
                }
                ir::Command::CopyTextureToTexture {
                    source,
                    source_rect,
                    destination,
                    destination_rect,
                } => {
                    let source =
                        self.ensure_image(*source, &mut resources, &mut external_bindings)?;
                    let destination =
                        self.ensure_image(*destination, &mut resources, &mut external_bindings)?;
                    operations.push(codegen::Operation::CopyTextureToTexture {
                        source,
                        source_rect: *source_rect,
                        destination,
                        destination_rect: *destination_rect,
                    });
                }
                ir::Command::BeginRenderPass(pass) => {
                    let target =
                        self.ensure_image(pass.target(), &mut resources, &mut external_bindings)?;
                    let depth = if let Some(depth) = pass.depth_attachment() {
                        Some(codegen::DepthAttachment {
                            target: self.ensure_image(
                                depth.target(),
                                &mut resources,
                                &mut external_bindings,
                            )?,
                            load: depth.load(),
                            store: depth.store(),
                        })
                    } else {
                        None
                    };
                    operations.push(codegen::Operation::BeginRenderPass(codegen::RenderPass {
                        target,
                        area: pass.area(),
                        load: pass.load(),
                        store: pass.store(),
                        depth,
                    }));
                }
                ir::Command::EndRenderPass => operations.push(codegen::Operation::EndRenderPass),
                ir::Command::SetPipeline(pipeline) => {
                    let pipeline = self.ensure_pipeline(*pipeline, &mut pipelines)?;
                    operations.push(codegen::Operation::SetPipeline(pipeline));
                }
                ir::Command::SetVertexBuffer { buffer, offset } => {
                    let buffer =
                        self.ensure_buffer(*buffer, &mut resources, &mut external_bindings)?;
                    operations.push(codegen::Operation::SetVertexBuffer {
                        buffer,
                        offset: *offset,
                    });
                }
                ir::Command::SetIndexBuffer {
                    buffer,
                    offset,
                    format,
                } => {
                    let buffer =
                        self.ensure_buffer(*buffer, &mut resources, &mut external_bindings)?;
                    operations.push(codegen::Operation::SetIndexBuffer {
                        buffer,
                        offset: *offset,
                        format: *format,
                    });
                }
                ir::Command::SetTexture(texture) => {
                    let texture =
                        self.ensure_image(*texture, &mut resources, &mut external_bindings)?;
                    operations.push(codegen::Operation::SetTexture(texture));
                }
                ir::Command::SetSampler(sampler) => {
                    let descriptor = self.resources.sampler(*sampler)?;
                    operations.push(codegen::Operation::SetSampler(descriptor));
                }
                ir::Command::SetUniforms(uniforms) => {
                    operations.push(codegen::Operation::SetUniforms(*uniforms));
                }
                ir::Command::SetScissor(scissor) => {
                    operations.push(codegen::Operation::SetScissor(*scissor));
                }
                ir::Command::Draw {
                    vertex_count,
                    first_vertex,
                } => operations.push(codegen::Operation::Draw {
                    vertex_count: *vertex_count,
                    first_vertex: *first_vertex,
                }),
                ir::Command::DrawIndexed {
                    index_count,
                    first_index,
                    base_vertex,
                } => operations.push(codegen::Operation::DrawIndexed {
                    index_count: *index_count,
                    first_index: *first_index,
                    base_vertex: *base_vertex,
                }),
                // The published 1.0 core has only fixed commands; development
                // cores also carry programmable operations, rejected preflight.
                #[allow(unreachable_patterns)]
                _ => {
                    return Err(IrSubmitError::Unsupported(
                        UnsupportedIrFeature::ProgrammableExecution,
                    ));
                }
            }
        }

        let mut pending = split_async_operations(&operations)?;
        pending.reverse();
        let mut chunks = Vec::new();
        let mut owned_bytes = 0usize;
        while let Some(operations) = pending.pop() {
            let result = prepare_chunk(
                context.device.codegen_capabilities,
                &resources,
                &pipelines,
                &operations,
                &external_bindings,
                0,
                native_limit,
            );
            match result {
                Ok((chunk, end)) => {
                    owned_bytes = owned_bytes
                        .checked_add(end as usize)
                        .and_then(|bytes| bytes.checked_add(chunk.compiled.words.len() * 4))
                        .filter(|bytes| *bytes <= MAX_LOGICAL_BYTES)
                        .ok_or(IrSubmitError::SubmissionTooLarge)?;
                    chunks
                        .try_reserve(1)
                        .map_err(|_| IrSubmitError::OutOfMemory)?;
                    chunks.push(chunk);
                }
                Err(
                    error @ (IrSubmitError::SubmissionTooLarge
                    | IrSubmitError::Codegen(codegen::CompileError::CommandBudgetExceeded)),
                ) => {
                    let draws = operations
                        .iter()
                        .filter(|operation| {
                            matches!(
                                operation,
                                codegen::Operation::Draw { .. }
                                    | codegen::Operation::DrawIndexed { .. }
                            )
                        })
                        .count();
                    if draws <= 1 {
                        return Err(error);
                    }
                    let retry = split_submission_operations(&operations, (draws / 2).max(1))?;
                    if retry.len() <= 1 {
                        return Err(error);
                    }

                    pending
                        .try_reserve(retry.len())
                        .map_err(|_| IrSubmitError::OutOfMemory)?;
                    pending.extend(retry.into_iter().rev());
                }
                Err(error) => return Err(error),
            }
        }
        Ok((chunks, external_bindings))
    }
}
