schema_version = 2

[project]
name = "scarlet-aarch64-switch-console"

[bsp]
path = "bsp"
package = "scarlet"

[bsp.kernel]
source = { path = "../../../Scarlet/kernel" }
features = { linux-boot = true, limine = false, hypervisor = false, network = true, user-fpu = true, user-vector = true }

[modules]
"scarlet-driver-tegra210" = { path = "../../drivers/soc/tegra210", enabled = true }
"scarlet-driver-tegra210-cpufreq" = { path = "../../drivers/cpufreq/tegra210", enabled = true }
"scarlet-driver-nvidia-gm20b" = { path = "../../drivers/gpu/nvidia-gm20b", enabled = true }
"scarlet-driver-tegra210-dc" = { path = "../../drivers/display/tegra210-dc", enabled = true }
"scarlet-driver-max77620" = { path = "../../drivers/rtc/max77620", enabled = true }
"scarlet-driver-tegra210-sdhci" = { path = "../../drivers/mmc/tegra210-sdhci", enabled = true }
"scarlet-driver-stm-ftm4" = { path = "../../drivers/input/touchscreen/stm-ftm4", enabled = true }
"scarlet-driver-joycon" = { path = "../../drivers/input/joycon", enabled = true }

[images.initramfs]
format = "newc"
output = ".scarlet/images/initramfs.cpio"

[[images.initramfs.layers]]
kind = "bundle"
path = ".scarlet/console-bundle.toml"

[[images.initramfs.layers]]
kind = "copy"
source = "initramfs"
to = "/"

[hooks.post-image]
command = "tools/package-l4t.sh"
