// SPDX-License-Identifier: GPL-2.0-only
//! Private immutable executable snapshots. Only a validated package can be
//! materialized; hardware SPH words are always generated by the verifier.
use alloc::{boxed::Box, vec::Vec};
use maxwell_program_wire::{Error, Limits, Metadata, Program, Stage, Validated};

pub const ENTRY_OFFSET: usize = 0x30;
pub const CODE_OFFSET: usize = 0x80;
pub const ARENA_ALIGNMENT: usize = 4096;

pub struct Snapshot {
    bytes: Box<[u8]>,
    validated: Validated,
    metadata: Metadata,
}

impl Snapshot {
    /// Caller must obtain these bytes through its checked attachment mapping,
    /// before submitting any GPU work. The owned allocation cannot subsequently
    /// be exposed to userspace, imported attachments, or GPU write commands.
    pub fn from_private_bytes(bytes: Box<[u8]>, limits: &Limits) -> Result<Self, Error> {
        let p = Program::parse(&bytes)?;
        let validated = maxwell_program_wire::validate(&p, limits)?;
        let metadata = p.metadata;
        Ok(Self {
            bytes,
            validated,
            metadata,
        })
    }

    pub fn copy_from(bytes: &[u8], limits: &Limits) -> Result<Self, Error> {
        if bytes.len() < maxwell_program_wire::HEADER_SIZE
            || bytes.len() > maxwell_program_wire::HEADER_SIZE + maxwell_program_wire::MAX_CODE_SIZE
        {
            return Err(Error::Size);
        }
        Self::from_private_bytes(Vec::from(bytes).into_boxed_slice(), limits)
    }

    pub fn stage(&self) -> Stage {
        self.validated.stage
    }
    pub fn gprs(&self) -> u32 {
        self.validated.gprs as u32
    }
    pub fn resource_mask(&self) -> u64 {
        self.validated.resource_mask
    }
    pub fn cb_sizes(&self) -> &[u32; 32] {
        &self.validated.cb_sizes
    }
    pub fn metadata(&self) -> &Metadata {
        &self.metadata
    }
    pub fn attr_in(&self) -> &[u32; 4] {
        &self.metadata.attr_in
    }
    pub fn attr_out(&self) -> &[u32; 4] {
        &self.metadata.attr_out
    }
    pub fn fs_color_mask(&self) -> u32 {
        self.metadata.fs_color_mask
    }
    pub fn max_control_depth(&self) -> u8 {
        self.validated.max_control_depth
    }
    pub fn code_len(&self) -> usize {
        self.bytes.len() - maxwell_program_wire::HEADER_SIZE
    }
    pub fn arena_len(&self) -> usize {
        (CODE_OFFSET + self.code_len()).next_multiple_of(ARENA_ALIGNMENT)
    }

    /// The destination is a separate kernel-owned executable allocation. It
    /// must never also serve as a public attachment or copy destination.
    pub fn materialize(&self, destination: &mut [u8]) -> Result<(), Error> {
        if destination.len() != self.arena_len() {
            return Err(Error::Size);
        }
        destination.fill(0);
        for (i, word) in self.validated.header.iter().enumerate() {
            destination[ENTRY_OFFSET + i * 4..ENTRY_OFFSET + i * 4 + 4]
                .copy_from_slice(&word.to_le_bytes());
        }
        destination[CODE_OFFSET..CODE_OFFSET + self.code_len()]
            .copy_from_slice(&self.bytes[maxwell_program_wire::HEADER_SIZE..]);
        Ok(())
    }
}
