[package]
name = "scarlet-driver-tegra210-cpufreq"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"

[target.'cfg(target_os = "none")'.dependencies]
scarlet = { git = "https://github.com/petitstrawberry/Scarlet", rev = "0b0fe0df501f7e2615be31a4ad2b0d256a20700a", default-features = false, features = ["network"] }
scarlet-driver-tegra210 = { path = "../../soc/tegra210" }
fdt = "0.1.5"
