// Generated by generate.py from FFmpeg software-decoded NV12.
pub const BASELINE: &[u8] = include_bytes!("baseline.h264");
pub const BASELINE_HASHES: [u64; 12] = [
    0x8ba372fe4eb79666,
    0xe26cdab732fe10b1,
    0xd2abd3ceb6723253,
    0xf3d4883b4fe22eed,
    0xef9d11914c0d48b5,
    0xa2e0e11dcf7a7f07,
    0xb2208df79c5255e2,
    0xc4685cf8e5fe9f26,
    0xfc245abf7a3b106f,
    0xb2548355f8a9c868,
    0xdac9460db95e310d,
    0x3878bc4f3083d3ce,
];
#[cfg(test)]
pub const BASELINE_ORDER: [usize; 12] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];
pub const HIGH: &[u8] = include_bytes!("high.h264");
pub const HIGH_HASHES: [u64; 24] = [
    0x2c8b0ec338d6a032,
    0xf544778550aa5cbf,
    0x98e93aec14d6f8a4,
    0x6997cfcaab0ad7f1,
    0x2d3c91c389483266,
    0x56b81df8557db4c9,
    0x8385880926226eac,
    0x178d012248723f78,
    0x0ca290bf43b01aec,
    0x1c84d2ef0302d8db,
    0x6aa03dd15f887ee2,
    0x96806fd4c2d5823b,
    0x808050f755877eb8,
    0xf0cb1eea35e73b9e,
    0x141489af552481aa,
    0x430322e87aa66e5d,
    0x8185b14f012f164a,
    0xd154c703da547a9a,
    0x824452ef2a919dc3,
    0x6e31f1924babb6c5,
    0x0d3c5a070b49bd92,
    0xdd8b928a3de5cc4c,
    0xefb5ee1911a65776,
    0x522f003c85b30f43,
];
#[cfg(test)]
pub const HIGH_ORDER: [usize; 24] = [
    0, 3, 1, 2, 5, 4, 8, 6, 7, 11, 9, 10, 13, 12, 16, 14, 15, 19, 17, 18, 21, 20, 23, 22,
];
