[package]
name = "nvdec-qa"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"

[target.'cfg(target_os = "scarlet")'.dependencies]
scarlet-video-client = { git = "https://github.com/petitstrawberry/Scarlet", rev = "d3b1c05127d4df3616f988b81a99f616e8a88064", default-features = false, features = ["std", "h264-stateless-hw"] }

[dev-dependencies]
scarlet-codecs = { git = "https://github.com/petitstrawberry/Scarlet", rev = "d3b1c05127d4df3616f988b81a99f616e8a88064", features = ["h264"] }
