#!/usr/bin/env python3
"""Regenerate procedural H.264 fixtures and decode-order NV12 checksums."""
import json
from pathlib import Path
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parent
CASES = [
    ("baseline", 160, 90, 12, "keyint=12:min-keyint=12:scenecut=0:bframes=0:ref=2:aud=1:slices=1"),
    ("high", 320, 180, 24, "keyint=24:min-keyint=24:scenecut=0:bframes=2:ref=3:aud=1:slices=3"),
]


def fnv(data):
    result = 0xcbf29ce484222325
    for byte in data:
        result = ((result ^ byte) * 0x100000001b3) & ((1 << 64) - 1)
    return result


lines = ["// Generated by generate.py from FFmpeg software-decoded NV12."]
with tempfile.TemporaryDirectory() as directory:
    raw = Path(directory) / "frame.nv12"
    for name, width, height, count, options in CASES:
        encoded = ROOT / "src" / f"{name}.h264"
        subprocess.run([
            "ffmpeg", "-y", "-hide_banner", "-loglevel", "error", "-f", "lavfi",
            "-i", f"testsrc2=size={width}x{height}:rate=12", "-frames:v", str(count),
            "-c:v", "libx264", "-profile:v", name, "-pix_fmt", "yuv420p",
            "-x264-params", options, "-f", "h264", str(encoded),
        ], check=True)
        subprocess.run([
            "ffmpeg", "-y", "-hide_banner", "-loglevel", "error", "-i", str(encoded),
            "-fps_mode", "passthrough", "-pix_fmt", "nv12", "-f", "rawvideo", str(raw),
        ], check=True)
        frames = json.loads(subprocess.check_output([
            "ffprobe", "-v", "error", "-select_streams", "v:0", "-show_entries",
            "frame=pkt_pos", "-of", "json", str(encoded),
        ]))["frames"]
        # FFmpeg emits display order. Packet file positions independently map
        # each decoded picture back to the access unit submitted to hardware.
        positions = sorted(int(frame["pkt_pos"]) for frame in frames)
        data = raw.read_bytes()
        size = width * height * 3 // 2
        assert len(frames) == count and len(data) == size * count
        hashes, order = [0] * count, [0] * count
        for display, frame in enumerate(frames):
            decode = positions.index(int(frame["pkt_pos"]))
            hashes[decode] = fnv(data[display * size:(display + 1) * size])
            order[decode] = display
        prefix = name.upper()
        lines.append(f'pub const {prefix}: &[u8] = include_bytes!("{name}.h264");')
        lines.append(f"pub const {prefix}_HASHES: [u64; {count}] = [")
        lines.extend(f"    0x{value:016x}," for value in hashes)
        lines.append("];")
        lines.append("#[cfg(test)]")
        lines.append(f"pub const {prefix}_ORDER: [usize; {count}] = {order!r};")
(ROOT / "src" / "fixtures.rs").write_text("\n".join(lines) + "\n")
