# Stem Daemon Configuration File
# stemd registers itself as a service to manage its dependencies

[service.sws]
exec = "/bin/sws"
order = 01
depends = ["sbusd", "sas"]
ready_notify = true
ready_timeout_ms = 5000

[service.scarlet-desktop]
exec = "/bin/scarlet-desktop --shell-mode console"
depends = ["sws"]
