[package]
name = "scarlet-driver-tegra210-xusb"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"

[target.'cfg(target_os = "none")'.dependencies]
scarlet = { git = "https://github.com/petitstrawberry/Scarlet", rev = "cfe8b57bca7d3407e108c3cdf43e0a9fd7dac030", default-features = false, features = ["network"] }
scarlet-driver-tegra210 = { path = "../../soc/tegra210" }
scarlet-driver-max77620 = { path = "../../rtc/max77620" }
