[package]
name = "sgfx-codegen-maxwell"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"

[lib]
path = "src/lib.rs"

[dependencies]
maxwell-shader-pack = { path = "../../shared/maxwell-shader-pack" }
maxwell-submit-wire = { path = "../../shared/maxwell-submit-wire" }
sgfx-core = { git = "https://github.com/petitstrawberry/sgfx", rev = "0213c76bdc9777ddb2a3a25e30b54ac8c5e01912", default-features = false }
