[package]
name = "sgfx-codegen-maxwell"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"

[lib]
path = "src/lib.rs"

[dependencies]
maxwell-shader-pack = { path = "../../shared/maxwell-shader-pack" }
maxwell-submit-wire = { path = "../../shared/maxwell-submit-wire" }
sgfx-core = { git = "https://github.com/petitstrawberry/sgfx", rev = "ddf00563c617a30bbf64fa5dbe8152c852d493f9", default-features = false }
