use maxwell_program_wire::*;

const TRUE: u64 = 7 << 16;
const NOP: u64 = (0x50b0u64 << 48) | TRUE | 0xf00;
const EXIT: u64 = (0xe300u64 << 48) | TRUE | 0xf;
fn bytes(words: &[u64]) -> Vec<u8> {
    let mut v = Vec::new();
    let schedule = 0x7e0u64 | (0x7e0u64 << 21) | (0x7e0u64 << 42);
    for group in words.chunks(3) {
        v.extend_from_slice(&schedule.to_le_bytes());
        for i in 0..3 {
            v.extend_from_slice(&group.get(i).copied().unwrap_or(NOP).to_le_bytes());
        }
    }
    v
}
fn ip(index: usize) -> usize {
    index / 3 * 32 + 8 + index % 3 * 8
}
fn jump(op: u16, source: usize, target: usize, pred: u64) -> u64 {
    let relative = ip(target) as i64 - ip(source) as i64 - 8;
    (op as u64) << 48 | pred | 0xf | ((relative as u64 & 0xffffff) << 20)
}
fn check(words: &[u64], m: Metadata) -> Result<Validated, Error> {
    validate(
        &Program {
            metadata: m,
            code: &bytes(words),
        },
        &Limits {
            cb_sizes: m.cb_sizes,
            resource_mask: m.resource_mask,
        },
    )
}

#[test]
fn stage_package_roundtrip_reserved_fields_and_generated_header() {
    let mut m = Metadata::new(Stage::Vertex);
    m.attr_in[0] = 15;
    m.sysvals_out_ab = 0xf0000000;
    m.store_req_start = 28;
    m.store_req_end = 31;
    let code = bytes(&[NOP, EXIT]);
    let mut wire = vec![0; HEADER_SIZE + code.len()];
    Program {
        metadata: m,
        code: &code,
    }
    .encode_into(&mut wire)
    .unwrap();
    let parsed = Program::parse(&wire).unwrap();
    assert_eq!(parsed.metadata, m);
    assert_eq!(parsed.code, code);
    let valid = validate(
        &parsed,
        &Limits {
            cb_sizes: [0; 32],
            resource_mask: 0,
        },
    )
    .unwrap();
    assert_eq!(valid.header[0], 0x00020461);
    assert_eq!(&valid.header[1..4], &[0; 3]);
    assert_eq!(valid.header[6], 15);
    wire[400] = 1;
    assert!(matches!(Program::parse(&wire), Err(Error::Format)));
    wire[400] = 0;
    wire[11] = 0;
    assert!(matches!(Program::parse(&wire), Err(Error::Format)));
}

#[test]
fn pinned_nak_sm52_vertex_and_fragment_golden_programs_are_accepted() {
    // Exact outputs in shared/sgfx-nak/tests/graphics.rs, produced by Mesa at
    // MESA_SHA, not hand-assembled surrogates. Compiler IO reflection is copied
    // into metadata; all hardware header words are regenerated by this crate.
    let vs: [u32; 16] = [
        0x1c400706, 0x003fb401, 0x0807ff00, 0xefd9ff80, 0x0707ff00, 0xeff1ff81, 0x0007000f,
        0xe3000000, 0xfc0007e2, 0x001f8000, 0x00070f00, 0x50b00000, 0x00070f00, 0x50b00000,
        0x00070f00, 0x50b00000,
    ];
    let fs: [u32; 16] = [
        0xe4200701, 0x001d0400, 0x0ff7ff00, 0xe003ff88, 0x4ff7ff01, 0xe003ff88, 0x8ff7ff02,
        0xe003ff88, 0xfda00762, 0x001f880f, 0xcff7ff03, 0xe003ff88, 0x0007000f, 0xe3000000,
        0x00070f00, 0x50b00000,
    ];
    let limits = Limits {
        cb_sizes: [0; 32],
        resource_mask: 0,
    };
    let mut m = Metadata::new(Stage::Vertex);
    m.gprs = 24;
    m.attr_in[0] = 15;
    m.sysvals_out_ab = 0xf0000000;
    m.store_req_start = 28;
    m.store_req_end = 31;
    let code: Vec<u8> = vs.into_iter().flat_map(u32::to_le_bytes).collect();
    let valid = validate(
        &Program {
            metadata: m,
            code: &code,
        },
        &limits,
    )
    .unwrap();
    assert_eq!(
        valid.header,
        [
            0x00020461, 0, 0, 0, 0x1f01c000, 0, 15, 0, 0, 0, 0, 0, 0, 0xf000, 0, 0, 0, 0, 0, 0
        ]
    );
    let mut m = Metadata::new(Stage::Fragment);
    m.gprs = 24;
    m.fs_color_mask = 15;
    m.fs_inputs[..4].fill(3);
    let code: Vec<u8> = fs.into_iter().flat_map(u32::to_le_bytes).collect();
    let valid = validate(
        &Program {
            metadata: m,
            code: &code,
        },
        &limits,
    )
    .unwrap();
    assert_eq!(
        valid.header,
        [
            0x25462, 0, 0, 0, 0, 0x80000000, 0xff, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 0
        ]
    );
}

#[test]
fn every_forbidden_external_family_is_rejected() {
    let m = Metadata::new(Stage::Vertex);
    // Includes global/local/shared loads and stores, surface read/write/atomic,
    // LDC even with RZ, memory barriers/cache ops, indirect attribute pointer,
    // bindless texture variants, geometry output, and indirect/call families.
    for op in [
        0xeed0, 0xef40, 0xef48, 0xeed8, 0xef50, 0xef58, 0xeb00, 0xeb20, 0xeac0, 0xea60, 0xebf8,
        0xee00, 0xed00, 0xec00, 0xef90, 0xef98, 0xef60, 0xef80, 0xefa0, 0xefd0, 0xdeb8, 0xdd38,
        0xdef8, 0xdf60, 0xde78, 0xdf50, 0xfbe0, 0xf6e0, 0xebe0, 0xe250, 0xe260, 0xe220,
    ] {
        for lower in [TRUE, TRUE | 0xffff | ((0xfffffff_u64) << 20), TRUE | 0xff00] {
            assert!(
                check(&[(op as u64) << 48 | lower, EXIT], m).is_err(),
                "opcode {op:04x}"
            );
        }
    }
}

#[test]
fn scheduler_reserved_bits_and_missing_exit_fail() {
    let m = Metadata::new(Stage::Vertex);
    let mut code = bytes(&[NOP, EXIT]);
    code[7] |= 0x80;
    assert_eq!(
        validate(
            &Program {
                metadata: m,
                code: &code
            },
            &Limits {
                cb_sizes: [0; 32],
                resource_mask: 0
            }
        )
        .unwrap_err(),
        Error::Scheduling
    );
    code = bytes(&[NOP, EXIT]);
    code[0] = (code[0] & !0xe0) | 0xc0;
    assert_eq!(
        validate(
            &Program {
                metadata: m,
                code: &code
            },
            &Limits {
                cb_sizes: [0; 32],
                resource_mask: 0
            }
        )
        .unwrap_err(),
        Error::Scheduling
    );
    assert_eq!(check(&[NOP, NOP, NOP], m).unwrap_err(), Error::Fallthrough);
}

#[test]
fn branch_destinations_are_signed_bounded_and_never_scheduler_words() {
    let m = Metadata::new(Stage::Vertex);
    for target in [-0x800000i64, -16, 16, 24, 0x7fffff] {
        let w = (0xe240u64 << 48) | TRUE | 0xf | ((target as u64 & 0xffffff) << 20);
        // First IP=8; +8 means target16+relative, so -16 lands scheduler0,
        // +16 lands scheduler32, +24 lies beyond this one bundle.
        assert_eq!(check(&[w, EXIT, NOP], m).unwrap_err(), Error::Branch);
    }
    assert!(check(&[jump(0xe240, 0, 1, TRUE), EXIT, NOP], m).is_ok());
}

#[test]
fn structured_if_and_loop_stacks_are_proven_from_code() {
    let m = Metadata::new(Stage::Vertex);
    let sync = (0xf0f8u64 << 48) | TRUE | 0xf;
    let conditional = 0u64;
    let valid = check(
        &[
            jump(0xe290, 0, 6, TRUE),
            jump(0xe240, 1, 4, conditional),
            NOP,
            sync,
            NOP,
            sync,
            EXIT,
        ],
        m,
    )
    .unwrap();
    assert_eq!(valid.max_control_depth, 1);
    let brk = (0xe340u64 << 48) | conditional | 0xf;
    let cont = (0xe350u64 << 48) | TRUE | 0xf;
    let valid = check(
        &[
            jump(0xe2a0, 0, 6, TRUE),
            jump(0xe2b0, 1, 1, TRUE),
            brk,
            cont,
            NOP,
            NOP,
            EXIT,
        ],
        m,
    )
    .unwrap();
    assert_eq!(valid.max_control_depth, 2);
    assert_eq!(check(&[sync, EXIT], m).unwrap_err(), Error::ControlStack);
    assert_eq!(
        check(&[jump(0xe290, 0, 2, conditional), NOP, EXIT], m).unwrap_err(),
        Error::ControlStack
    );
    // Re-entering a push without popping cannot grow an unchecked spill stack.
    assert_eq!(
        check(
            &[jump(0xe290, 0, 2, TRUE), jump(0xe240, 1, 0, TRUE), EXIT],
            m
        )
        .unwrap_err(),
        Error::ControlStack
    );
    let mut deep = Vec::new();
    for i in 0..17 {
        deep.push(jump(0xe290, i, 17, TRUE));
    }
    deep.push(EXIT);
    assert_eq!(check(&deep, m).unwrap_err(), Error::ControlStack);
}

#[test]
fn immediate_constant_reads_cannot_exceed_declared_or_authorized_extents() {
    let mut m = Metadata::new(Stage::Vertex);
    m.cb_sizes[0] = 16;
    let mov = |offset: u64| (0x4c98u64 << 48) | TRUE | (offset / 4) << 20 | (0xfu64 << 39);
    assert!(check(&[mov(12), EXIT], m).is_ok());
    assert_eq!(
        check(&[mov(16), EXIT], m).unwrap_err(),
        Error::ConstantBuffer
    );
    let code = bytes(&[mov(12), EXIT]);
    assert_eq!(
        validate(
            &Program {
                metadata: m,
                code: &code
            },
            &Limits {
                cb_sizes: [0; 32],
                resource_mask: 0
            }
        )
        .unwrap_err(),
        Error::Resource
    );
    let mut corrupted = mov(12);
    corrupted |= 1 << 34; // choose absent constant bank1
    assert_eq!(
        check(&[corrupted, EXIT], m).unwrap_err(),
        Error::ConstantBuffer
    );
}

#[test]
fn texture_resource_slots_are_authorized_and_never_bindless() {
    let mut m = Metadata::new(Stage::Fragment);
    m.resource_mask = 1;
    let tex = |handle: u64| {
        let variables = ((1u64 << 13) - 1) << 36 | (3u64 << 55);
        ((0x0380u64 << 48) & !variables)
            | TRUE
            | 0xff00
            | (255u64 << 20)
            | (2 << 28)
            | (15 << 31)
            | (handle << 36)
    };
    assert!(check(&[tex(8), EXIT], m).is_ok());
    for handle in [0, 7, 9, 72, 8191] {
        assert_eq!(check(&[tex(handle), EXIT], m).unwrap_err(), Error::Resource);
    }
    let code = bytes(&[tex(8), EXIT]);
    assert_eq!(
        validate(
            &Program {
                metadata: m,
                code: &code
            },
            &Limits {
                cb_sizes: [0; 32],
                resource_mask: 0
            }
        )
        .unwrap_err(),
        Error::Resource
    );
}

#[test]
fn untrusted_metadata_does_not_enable_io_or_unknown_system_registers() {
    let m = Metadata::new(Stage::Vertex);
    let ald = (0xefd8u64 << 48) | TRUE | 0xff00 | (255u64 << 39) | (0x80 << 20);
    assert_eq!(check(&[ald, EXIT], m).unwrap_err(), Error::Attribute);
    let mut allowed = m;
    allowed.attr_in[0] = 1;
    assert!(check(&[ald, EXIT], allowed).is_ok());
    assert!(check(&[ald ^ (1 << 8), EXIT], allowed).is_err());
    let sr = |idx: u64| (0xf0c8u64 << 48) | TRUE | (idx << 20);
    assert!(check(&[sr(0), EXIT], m).is_ok());
    for idx in [2, 3, 4, 0x1d, 0x50, 0xff] {
        assert_eq!(check(&[sr(idx), EXIT], m).unwrap_err(), Error::Instruction);
    }
}

#[test]
fn random_wire_data_never_panics_or_authorizes_forbidden_instruction() {
    let mut seed = 0x6a09e667f3bcc909u64;
    let m = Metadata::new(Stage::Fragment);
    for _ in 0..20_000 {
        seed ^= seed << 13;
        seed ^= seed >> 7;
        seed ^= seed << 17;
        let _ = check(&[seed, EXIT], m);
        let mut wire = vec![0u8; HEADER_SIZE + 32];
        Program {
            metadata: m,
            code: &bytes(&[NOP, EXIT]),
        }
        .encode_into(&mut wire)
        .unwrap();
        let index = (seed as usize) % wire.len();
        wire[index] ^= (seed >> 32) as u8;
        if let Ok(p) = Program::parse(&wire) {
            let _ = validate(
                &p,
                &Limits {
                    cb_sizes: [0; 32],
                    resource_mask: 0,
                },
            );
        }
    }
}
