[package]
name = "gm20b-depth-qa"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"

[dependencies]
sgfx-codegen-maxwell = { path = "../../userspace/sgfx-codegen-maxwell" }
maxwell-submit-wire = { path = "../../shared/maxwell-submit-wire" }
sgfx-core = { git = "https://github.com/petitstrawberry/sgfx", rev = "ddf00563c617a30bbf64fa5dbe8152c852d493f9", default-features = false }

[target.'cfg(target_os = "scarlet")'.dependencies]
gpu-raw = { git = "https://github.com/petitstrawberry/Scarlet", rev = "e027956300006bd8a41c42691c6925c63039fd43", default-features = false, features = ["std"] }
scarlet-os = { git = "https://github.com/petitstrawberry/Scarlet", rev = "e027956300006bd8a41c42691c6925c63039fd43", default-features = false, features = ["std"] }
