# Switch uses the Tegra210 stateless H.264 backend.
[[layers]]
kind = "cargo"
source = { git = "https://github.com/petitstrawberry/Scarlet", rev = "3ecfef43b8223e2b76f6b852a364d9cc38876913" }
subdir = "user/video_player"
package = "video_player"
bin = "video-player"
default-features = false
features = ["h264-stateless-hw", "mp4-aac"]
replace = true
to = "/bin/video-player"
