# Switch uses the Tegra210 stateless H.264 backend.
[[layers]]
kind = "cargo"
source = { git = "https://github.com/petitstrawberry/Scarlet", rev = "0b0fe0df501f7e2615be31a4ad2b0d256a20700a" }
subdir = "user/video_player"
package = "video_player"
bin = "video-player"
default-features = false
features = ["h264-stateless-hw", "mp4-aac"]
replace = true
to = "/bin/video-player"
