# Switch uses the Tegra210 stateless H.264 backend.
[[layers]]
kind = "cargo"
source = { git = "https://github.com/petitstrawberry/Scarlet", rev = "616f6ad06643587f7c5270a692131d4cfaabfa6a" }
subdir = "user/video_player"
package = "video_player"
bin = "video-player"
default-features = false
features = ["h264-stateless-hw", "mp4-aac"]
replace = true
to = "/bin/video-player"
