#!/usr/bin/env python3
"""Reuse Scarlet's normal base, CLI and desktop layers for a RAM-only console."""
import hashlib
import json
import os
from pathlib import Path
import shlex
import shutil
import subprocess
import sys
import tomllib

ROOT = Path(__file__).resolve().parents[1]
PROJECT = ROOT / "projects/aarch64-switch-console"
SCARLET = ROOT.parent / "Scarlet"
DESKTOP_BINS = {
    "scarlet-desktop", "desktop-settings", "files", "notepad", "scarlet-shell",
    "terminal", "sws", "sas", "sasctl", "settings", "task-manager", "clock",
    "sgfx-probe", "sgfx-cube", "sgfx-showcase", "ui-sgfx-showcase", "ui-benchmark",
}


def value(item):
    if isinstance(item, bool):
        return str(item).lower()
    if isinstance(item, str):
        return json.dumps(item, ensure_ascii=False)
    if isinstance(item, list):
        return "[" + ", ".join(map(value, item)) + "]"
    if isinstance(item, dict):
        return "{ " + ", ".join(f"{value(k)} = {value(v)}" for k, v in item.items()) + " }"
    return str(item)


def flatten(path):
    for original in tomllib.loads(path.read_text())["layers"]:
        layer = dict(original)
        if layer["kind"] == "bundle":
            yield from flatten((path.parent / layer["path"]).resolve())
            continue
        if path.parent.name == "desktop":
            if layer["kind"] == "cargo" and layer.get("bin") not in DESKTOP_BINS:
                continue
            if layer["kind"] == "script":
                continue
        source = layer.get("source")
        if isinstance(source, str):
            layer["source"] = str((path.parent / source).resolve())
        yield layer


def main():
    sgfx = Path(os.environ.get("SCARLET_SGFX_SOURCE", ROOT.parent / "sgfx")).resolve()
    sgfx_manifest = tomllib.loads((sgfx / "crates/sgfx/Cargo.toml").read_text())
    if "backend-scarlet-maxwell" not in sgfx_manifest.get("features", {}).get("default", []):
        raise SystemExit(
            f"SGFX checkout {sgfx} does not enable the Maxwell backend; "
            "set SCARLET_SGFX_SOURCE to a compatible checkout"
        )
    subprocess.run([sys.executable, str(ROOT / "scripts/verify-maxwell-shaders.py")], check=True)
    subprocess.run([sys.executable, str(ROOT / "scripts/prepare-gm20b-firmware.py")], check=True)
    cache = PROJECT / ".scarlet/cache"
    cargo_home = cache / "cargo-home"
    cargo_home.mkdir(parents=True, exist_ok=True)
    # Remove only the config generated by the previous A57/build-std flow.
    legacy_config = cargo_home / "config.toml"
    if legacy_config.is_file():
        contents = legacy_config.read_text()
        if ("target-cpu=cortex-a57" in contents
                and "target-feature=-lse" in contents
                and '[patch."https://github.com/petitstrawberry/scarlet-ui"]' in contents):
            legacy_config.unlink()
    for name in ("registry", "git"):
        link = cargo_home / name
        shared = Path.home() / ".cargo" / name
        if not link.exists() and shared.exists():
            link.symlink_to(shared, target_is_directory=True)
    layers = list(flatten(SCARLET / "bundles/desktop/bundle.toml"))
    layers.append({"kind": "copy", "source": str(PROJECT / ".scarlet/gm20b-firmware"), "to": "/"})
    # Keep the original desktop assets and configuration, including the
    # resident Files service. Catalog entries and optional services must match
    # the applications actually installed by this first RAM-only image.
    desktop_source = SCARLET / "bundles/desktop/fs"
    desktop_fs = PROJECT / ".scarlet/desktop-fs"
    if desktop_fs.exists():
        shutil.rmtree(desktop_fs)
    shutil.copytree(desktop_source, desktop_fs)
    installed = {layer["to"] for layer in layers if layer["kind"] == "cargo"}
    for entry in (desktop_fs / "etc/stemd.d/apps").glob("*.desktop"):
        commands = [line.split("=", 1)[1] for line in entry.read_text().splitlines() if line.startswith("Exec=")]
        if commands and shlex.split(commands[0])[0] not in installed:
            entry.unlink()
    for entry in (desktop_fs / "etc/stemd.d/services").glob("*.toml"):
        # stemd accepts legacy order = 01 syntax, which strict TOML rejects.
        commands = [shlex.split(line.split("=", 1)[1].strip())[0]
                    for line in entry.read_text().splitlines()
                    if line.split("=", 1)[0].strip() == "exec"]
        if any(shlex.split(command)[0] not in installed for command in commands):
            entry.unlink()
    for layer in layers:
        if layer["kind"] == "copy" and layer["source"] == str(desktop_source):
            layer["source"] = str(desktop_fs)
    text = "\n\n".join("[[layers]]\n" + "\n".join(f"{key} = {value(item)}" for key, item in layer.items()) for layer in layers)
    (PROJECT / ".scarlet/console-bundle.toml").write_text(text + "\n")
    pins = json.loads((PROJECT / "bootstack.json").read_text())["files"]
    stack = PROJECT / ".scarlet/bootstack"
    stack.mkdir(parents=True, exist_ok=True)
    for name, expected in pins.items():
        source = ROOT / "projects/aarch64-switch-l4t/.scarlet/bootstack" / name
        if not source.is_file() or hashlib.sha256(source.read_bytes()).hexdigest() != expected:
            raise SystemExit("import the pinned Noble bootstack with scripts/prepare-bootstack.py first")
        shutil.copyfile(source, stack / name)
    print(f"Prepared {len(layers)} normal distribution layers")


if __name__ == "__main__":
    main()
