#!/usr/bin/env python3
"""Prepare pinned sources, firmware and bootstack for the SD-root console."""
import hashlib
import json
import argparse
from pathlib import Path
import subprocess
import sys
import tomllib
from project_sources import pins, prepare, refresh_pinned_dependencies

ROOT = Path(__file__).resolve().parents[1]
PROJECT = ROOT / "projects/aarch64-switch-l4t-console"


def value(item):
    if isinstance(item, bool):
        return str(item).lower()
    if isinstance(item, str):
        return json.dumps(item, ensure_ascii=False)
    if isinstance(item, list):
        return "[" + ", ".join(map(value, item)) + "]"
    if isinstance(item, dict):
        return "{ " + ", ".join(f"{value(k)} = {value(v)}" for k, v in item.items()) + " }"
    return str(item)


def full_layers(path, sources):
    """Retain the complete upstream distribution with this project's source pins."""
    for original in tomllib.loads(path.read_text())["layers"]:
        layer = dict(original)
        if layer["kind"] == "bundle":
            yield from full_layers((path.parent / layer["path"]).resolve(), sources)
            continue
        source = layer.get("source")
        if isinstance(source, str):
            layer["source"] = str((path.parent / source).resolve())
        elif isinstance(source, dict) and source.get("git", "").removesuffix(".git") in sources:
            layer["source"] = str(sources[source["git"].removesuffix(".git")])
        yield layer


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--published", action="store_true",
                        help="ignore local source overrides and use the public pins")
    args = parser.parse_args()
    if args.published and (PROJECT / "scarlet.local.toml").exists():
        parser.error("published builds require removing the project's scarlet.local.toml override")
    checkouts = prepare(published=args.published)
    sgfx = checkouts["sgfx"]
    sgfx_manifest = tomllib.loads((sgfx / "crates/sgfx/Cargo.toml").read_text())
    if "backend-scarlet-maxwell" not in sgfx_manifest.get("features", {}).get("default", []):
        raise SystemExit(
            f"SGFX checkout {sgfx} does not enable the Maxwell backend; "
            "select a compatible pinned revision or an explicit local source override"
        )
    subprocess.run([sys.executable, str(ROOT / "scripts/verify-maxwell-shaders.py")], check=True)
    subprocess.run([sys.executable, str(ROOT / "scripts/prepare-gm20b-firmware.py")], check=True)
    sources = {pin["git"].removesuffix(".git"): checkouts[name] for name, pin in pins().items()}
    bundles = checkouts["scarlet"] / "bundles"
    for name, inputs in {
        "initramfs": [bundles / "base/bundle.toml", bundles / "cli-utils/bundle.toml"],
        "full": [bundles / "full/bundle.toml", PROJECT / "bundles/nvdec-player.toml"],
    }.items():
        # Canonical paths avoid treating a source symlink and its destination
        # as two separate Cargo packages in the same dependency graph.
        layers = [layer for path in inputs for layer in full_layers(path, sources)]
        text = "\n\n".join("[[layers]]\n" + "\n".join(f"{key} = {value(item)}" for key, item in layer.items()) for layer in layers)
        (PROJECT / f".scarlet/{name}-bundle.toml").write_text(text + "\n")
    cache = PROJECT / ".scarlet/cache"
    cargo_home = cache / "cargo-home"
    cargo_home.mkdir(parents=True, exist_ok=True)
    # Remove only the config generated by the previous A57/build-std flow.
    legacy_config = cargo_home / "config.toml"
    if legacy_config.is_file():
        contents = legacy_config.read_text()
        if ("target-cpu=cortex-a57" in contents
                and "target-feature=-lse" in contents
                and '[patch."https://github.com/petitstrawberry/scarlet-ui"]' in contents):
            legacy_config.unlink()
    for name in ("registry", "git"):
        link = cargo_home / name
        shared = Path.home() / ".cargo" / name
        if not link.exists() and shared.exists():
            link.symlink_to(shared, target_is_directory=True)
    for checkout in checkouts.values():
        refresh_pinned_dependencies(checkout, PROJECT / ".scarlet/userspace.toml")
    bootstack_pins = json.loads((PROJECT / "bootstack.json").read_text())["files"]
    stack = PROJECT / ".scarlet/bootstack"
    for name, expected in bootstack_pins.items():
        source = stack / name
        if not source.is_file() or hashlib.sha256(source.read_bytes()).hexdigest() != expected:
            raise SystemExit("import the pinned Noble bootstack with scripts/prepare-bootstack.py first")
    print("Prepared base + CLI initramfs and full SD rootfs dependencies")


if __name__ == "__main__":
    main()
