#!/usr/bin/env python3
"""Resolve immutable upstream commits and coordinate native SGFX clients."""
import argparse
import json
from pathlib import Path
import re
import subprocess
import tempfile
import tomllib

ROOT = Path(__file__).resolve().parents[1]
PROJECT = ROOT / "projects/aarch64-switch-l4t-console"
GENERATED = "# Generated by scripts/project_sources.py; do not edit.\n"
SGFX_URL = "https://github.com/petitstrawberry/sgfx"
UI_URL = "https://github.com/petitstrawberry/scarlet-ui"


def pins():
    result = tomllib.loads((ROOT / "source-pins.toml").read_text())
    for name, pin in result.items():
        if set(pin) != {"git", "rev"}:
            raise ValueError(f"{name}: only git and rev are allowed; local source patches are not supported")
        if not re.fullmatch(r"[0-9a-f]{40}", pin["rev"]):
            raise ValueError(f"{name}: expected a full commit ID")
    return result


def source(name):
    pin = pins()[name]
    if (ROOT / "source-paths.local.toml").exists():
        raise ValueError("source-paths.local.toml is no longer supported; use upstream commit pins")
    rev = pin["rev"]
    destination = ROOT / ".cache/sources" / name / rev
    if not destination.exists():
        destination.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.TemporaryDirectory(dir=destination.parent) as temporary:
            checkout = Path(temporary) / "checkout"
            subprocess.run(["git", "init", "--quiet", str(checkout)], check=True)
            subprocess.run(["git", "-C", str(checkout), "fetch", "--quiet",
                            "--depth=1", pin["git"], rev], check=True)
            subprocess.run(["git", "-C", str(checkout), "checkout", "--quiet",
                            "--detach", "FETCH_HEAD"], check=True)
            checkout.rename(destination)
    actual = subprocess.check_output(
        ["git", "-C", str(destination), "rev-parse", "HEAD"], text=True).strip()
    # Cargo may resolve lockfiles for a target or a bundle's feature selection.
    # Source and manifest edits, including new untracked files, are forbidden.
    status = subprocess.check_output([
        "git", "-C", str(destination), "status", "--porcelain", "--untracked-files=all",
        "--", ".", ":(exclude)Cargo.lock", ":(glob,exclude)**/Cargo.lock",
        ":(glob,exclude)**/__pycache__/**",
    ], text=True)
    if actual != rev or status:
        raise ValueError(f"{name}: cached source differs from its pin; remove the cache and fetch the upstream commit again")
    return destination


def write_generated(path, text):
    if path.exists() and not path.read_text().startswith(GENERATED):
        raise ValueError(f"refusing to replace non-generated Cargo configuration: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(mode="w", dir=path.parent, delete=False) as output:
        temporary = Path(output.name)
        try:
            output.write(text)
            output.flush()
        except BaseException:
            temporary.unlink(missing_ok=True)
            raise
    try:
        temporary.replace(path)
    finally:
        temporary.unlink(missing_ok=True)


def native_sgfx_config(checkout, project, ui_checkout=None):
    """Unify application pins on the selected public SGFX and UI releases.

    These Cargo replacements refer exclusively to the verified, immutable
    checkout. They never refer to a sibling worktree or edit upstream sources.
    Keep them out of the repository-wide config: the driver has its own locked
    build and communicates with the clients through ABI v2.
    """
    library = project.resolve() / ".scarlet/sgfx-maxwell/libsgfx_scarlet_maxwell.so"
    flags = ["--cfg", 'getrandom_backend="custom"', "-Zdefault-visibility=hidden",
             "-C", "link-arg=--dynamic-linker=/bin/scarlet-ld",
             "-C", "link-arg=--as-needed", "-C", f"link-arg={library}",
             "-C", "link-arg=--unresolved-symbols=ignore-all"]
    config = f'\n[target.aarch64-unknown-scarlet]\nrustflags = {json.dumps(flags)}\n'
    releases = [(SGFX_URL, checkout)]
    if ui_checkout is not None:
        releases.append((UI_URL, ui_checkout))
    for url, release in releases:
        config += f'\n[patch.{json.dumps(url)}]\n'
        for manifest in sorted((release / "crates").glob("*/Cargo.toml")):
            package = tomllib.loads(manifest.read_text())["package"]["name"]
            if url == SGFX_URL and package.endswith("-plugin"):
                continue
            config += f'{json.dumps(package)} = {{ path = {json.dumps(str(manifest.parent))} }}\n'
    return config


def prepare():
    checkouts = {name: source(name) for name in pins()}
    links = PROJECT / ".scarlet/sources"
    links.mkdir(parents=True, exist_ok=True)
    for name, checkout in checkouts.items():
        link = links / name
        if not link.is_symlink() and link.exists():
            raise ValueError(f"source link is occupied: {link}")
        # Publish atomically so a second build never sees an absent link or
        # collides with another preparation of the same pinned sources.
        with tempfile.TemporaryDirectory(dir=links) as temporary:
            replacement = Path(temporary) / "source"
            replacement.symlink_to(checkout, target_is_directory=True)
            replacement.replace(link)
    config = GENERATED + '\n[env]\n'
    for name, variable in (("scarlet", "SCARLET_SOURCE"), ("scarlet-ui", "SCARLET_UI_SOURCE")):
        config += f'{variable} = {{ value = {json.dumps(str(checkouts[name]))}, force = true }}\n'
    target = '\n[target.aarch64-unknown-scarlet]\n'
    target += 'rustflags = ["--cfg", \'getrandom_backend="custom"\']\n'
    write_generated(ROOT / ".cargo/config.toml", config + target)
    native = (native_sgfx_config(checkouts["sgfx"], PROJECT, checkouts.get("scarlet-ui"))
              if "sgfx" in checkouts else target)
    write_generated(PROJECT / ".scarlet/userspace.toml", config + native)
    return checkouts


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--published", action="store_true",
                        help="compatibility option; upstream commit pins are always used")
    parser.add_argument("--path", choices=list(pins()),
                        help="print one resolved source directory without preparing Cargo")
    args = parser.parse_args()
    if args.path:
        print(source(args.path))
    else:
        for name, path in prepare().items():
            print(f"{name}: {path}")


if __name__ == "__main__":
    main()
