#!/usr/bin/env python3
"""Resolve pinned public sources, with explicit optional local overrides."""
import argparse
import json
from pathlib import Path
import re
import subprocess
import tempfile
import tomllib

ROOT = Path(__file__).resolve().parents[1]
PROJECT = ROOT / "projects/aarch64-switch-l4t-console"
GENERATED = "# Generated by scripts/project_sources.py; do not edit.\n"


def pins():
    return tomllib.loads((ROOT / "source-pins.toml").read_text())


def source(name, *, published=False):
    pin = pins()[name]
    overrides = ROOT / "source-paths.local.toml"
    if not published and overrides.is_file():
        local = tomllib.loads(overrides.read_text()).get("paths", {}).get(name)
        if local:
            path = (ROOT / local).resolve(strict=True)
            if not path.is_dir():
                raise ValueError(f"{name}: source override is not a directory")
            return path
    rev = pin["rev"]
    if not re.fullmatch(r"[0-9a-f]{40}", rev):
        raise ValueError(f"{name}: expected a full commit ID")
    destination = ROOT / ".cache/sources" / name / rev
    if not destination.exists():
        destination.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.TemporaryDirectory(dir=destination.parent) as temporary:
            checkout = Path(temporary) / "checkout"
            subprocess.run(["git", "init", "--quiet", str(checkout)], check=True)
            subprocess.run(["git", "-C", str(checkout), "fetch", "--quiet",
                            "--depth=1", pin["git"], rev], check=True)
            subprocess.run(["git", "-C", str(checkout), "checkout", "--quiet",
                            "--detach", "FETCH_HEAD"], check=True)
            checkout.rename(destination)
    actual = subprocess.check_output(
        ["git", "-C", str(destination), "rev-parse", "HEAD"], text=True).strip()
    # Cargo rewrites lockfiles when applying the generated path overrides.
    # Every other tracked change must exactly match the recorded port patch.
    def source_diff():
        return subprocess.check_output([
            "git", "-C", str(destination), "diff", "--binary", "HEAD", "--", ".",
            ":(exclude)Cargo.lock", ":(glob,exclude)**/Cargo.lock",
        ], text=True)

    expected_diff = (ROOT / pin["patch"]).read_text() if "patch" in pin else ""
    if actual != rev:
        raise ValueError(f"{name}: cached source differs from its pin; use a local override for edits")
    if expected_diff and not source_diff():
        subprocess.run(["git", "-C", str(destination), "apply", "--check", str(ROOT / pin["patch"])], check=True)
        # Include newly added source files in subsequent exact patch checks.
        subprocess.run(["git", "-C", str(destination), "apply", "--intent-to-add",
                        str(ROOT / pin["patch"])], check=True)
    if source_diff() != expected_diff:
        raise ValueError(f"{name}: cached source differs from its pin; use a local override for edits")
    return destination


def packages(name, checkout):
    if name == "scarlet":
        manifests = [checkout / "kernel/Cargo.toml"]
        manifests += sorted((checkout / "user/lib").glob("*/Cargo.toml"))
    elif name in ("sgfx", "scarlet-ui"):
        manifests = sorted((checkout / "crates").glob("*/Cargo.toml"))
    else:
        manifests = sorted((checkout / "userspace").glob("*/Cargo.toml"))
    result = {}
    for manifest in manifests:
        package = tomllib.loads(manifest.read_text()).get("package", {})
        if "name" in package:
            result[package["name"]] = manifest.parent
    return result


def write_generated(path, text):
    if path.exists() and not path.read_text().startswith(GENERATED):
        raise ValueError(f"refusing to replace non-generated Cargo configuration: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(mode="w", dir=path.parent, delete=False) as output:
        temporary = Path(output.name)
        try:
            output.write(text)
            output.flush()
        except BaseException:
            temporary.unlink(missing_ok=True)
            raise
    try:
        temporary.replace(path)
    finally:
        temporary.unlink(missing_ok=True)


def refresh_pinned_dependencies(checkout, config):
    """Release old application lock entries so the pinned path patches apply.

    Cargo otherwise retains old, still-valid git versions after an upstream
    version bump. Limit the update to packages supplied by our source pins;
    unrelated dependencies keep their upstream lock entries.
    """
    lock = checkout / "Cargo.lock"
    if not lock.is_file() or not (checkout / "Cargo.toml").is_file():
        return
    patches = {url.removesuffix(".git"): packages for url, packages in
               tomllib.loads(config.read_text()).get("patch", {}).items()}
    updates = []
    for package in tomllib.loads(lock.read_text()).get("package", []):
        source = package.get("source", "")
        if not source.startswith("git+"):
            continue
        git_source = source.removeprefix("git+").split("#", 1)[0].split("?", 1)[0]
        url = git_source.removesuffix(".git")
        if package["name"] in patches.get(url, {}):
            updates += ["-p", f'{git_source}#{package["name"]}@{package["version"]}']
    if updates:
        subprocess.run(["cargo", "--config", str(config), "update", *updates],
                       cwd=checkout, check=True)


def prepare(*, published=False):
    checkouts = {name: source(name, published=published) for name in pins()}
    links = PROJECT / ".scarlet/sources"
    links.mkdir(parents=True, exist_ok=True)
    for name, checkout in checkouts.items():
        link = links / name
        if link.is_symlink():
            link.unlink()
        elif link.exists():
            raise ValueError(f"source link is occupied: {link}")
        link.symlink_to(checkout, target_is_directory=True)
    config = GENERATED
    for name, checkout in checkouts.items():
        replacements = packages(name, checkout)
        if not replacements:
            continue
        config += f'\n[patch.{json.dumps(pins()[name]["git"])}]\n'
        for package, directory in sorted(replacements.items()):
            config += f'{json.dumps(package)} = {{ path = {json.dumps(str(directory))} }}\n'
    config += '\n[patch."https://github.com/petitstrawberry/scarlet-project-switch"]\n'
    for package in ("sgfx-backend-scarlet-maxwell", "sgfx-codegen-maxwell"):
        config += f'{package} = {{ path = {json.dumps(str(ROOT / "userspace" / package))} }}\n'
    config += '\n[env]\n'
    for name, variable in (("scarlet", "SCARLET_SOURCE"), ("scarlet-ui", "SCARLET_UI_SOURCE")):
        config += f'{variable} = {{ value = {json.dumps(str(checkouts[name]))}, force = true }}\n'
    config += '\n[target.aarch64-unknown-scarlet]\n'
    config += 'rustflags = ["--cfg", \'getrandom_backend="custom"\']\n'
    # Cargo subprocesses in this tree and SDK builds from external package
    # directories must use the same source identities.
    write_generated(ROOT / ".cargo/config.toml", config)
    write_generated(PROJECT / ".scarlet/userspace.toml", config)
    return checkouts


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--published", action="store_true",
                        help="ignore local overrides and use only pinned public sources")
    parser.add_argument("--path", choices=list(pins()),
                        help="print one resolved source directory without preparing Cargo")
    args = parser.parse_args()
    if args.path:
        print(source(args.path, published=args.published))
    else:
        for name, path in prepare(published=args.published).items():
            print(f"{name}: {path}")


if __name__ == "__main__":
    main()
