#!/usr/bin/env python3
"""Resolve upstream commits without local source patches or dependency overrides."""
import argparse
import json
from pathlib import Path
import re
import subprocess
import tempfile
import tomllib

ROOT = Path(__file__).resolve().parents[1]
PROJECT = ROOT / "projects/aarch64-switch-l4t-console"
GENERATED = "# Generated by scripts/project_sources.py; do not edit.\n"


def pins():
    result = tomllib.loads((ROOT / "source-pins.toml").read_text())
    for name, pin in result.items():
        if set(pin) != {"git", "rev"}:
            raise ValueError(f"{name}: only git and rev are allowed; local source patches are not supported")
        if not re.fullmatch(r"[0-9a-f]{40}", pin["rev"]):
            raise ValueError(f"{name}: expected a full commit ID")
    return result


def source(name):
    pin = pins()[name]
    if (ROOT / "source-paths.local.toml").exists():
        raise ValueError("source-paths.local.toml is no longer supported; use upstream commit pins")
    rev = pin["rev"]
    destination = ROOT / ".cache/sources" / name / rev
    if not destination.exists():
        destination.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.TemporaryDirectory(dir=destination.parent) as temporary:
            checkout = Path(temporary) / "checkout"
            subprocess.run(["git", "init", "--quiet", str(checkout)], check=True)
            subprocess.run(["git", "-C", str(checkout), "fetch", "--quiet",
                            "--depth=1", pin["git"], rev], check=True)
            subprocess.run(["git", "-C", str(checkout), "checkout", "--quiet",
                            "--detach", "FETCH_HEAD"], check=True)
            checkout.rename(destination)
    actual = subprocess.check_output(
        ["git", "-C", str(destination), "rev-parse", "HEAD"], text=True).strip()
    # Cargo may resolve lockfiles for a target or a bundle's feature selection.
    # Source and manifest edits, including new untracked files, are forbidden.
    status = subprocess.check_output([
        "git", "-C", str(destination), "status", "--porcelain", "--untracked-files=all",
        "--", ".", ":(exclude)Cargo.lock", ":(glob,exclude)**/Cargo.lock",
        ":(glob,exclude)**/__pycache__/**",
    ], text=True)
    if actual != rev or status:
        raise ValueError(f"{name}: cached source differs from its pin; remove the cache and fetch the upstream commit again")
    return destination


def write_generated(path, text):
    if path.exists() and not path.read_text().startswith(GENERATED):
        raise ValueError(f"refusing to replace non-generated Cargo configuration: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(mode="w", dir=path.parent, delete=False) as output:
        temporary = Path(output.name)
        try:
            output.write(text)
            output.flush()
        except BaseException:
            temporary.unlink(missing_ok=True)
            raise
    try:
        temporary.replace(path)
    finally:
        temporary.unlink(missing_ok=True)


def prepare():
    checkouts = {name: source(name) for name in pins()}
    links = PROJECT / ".scarlet/sources"
    links.mkdir(parents=True, exist_ok=True)
    for name, checkout in checkouts.items():
        link = links / name
        if not link.is_symlink() and link.exists():
            raise ValueError(f"source link is occupied: {link}")
        # Publish atomically so a second build never sees an absent link or
        # collides with another preparation of the same pinned sources.
        with tempfile.TemporaryDirectory(dir=links) as temporary:
            replacement = Path(temporary) / "source"
            replacement.symlink_to(checkout, target_is_directory=True)
            replacement.replace(link)
    config = GENERATED + '\n[env]\n'
    for name, variable in (("scarlet", "SCARLET_SOURCE"), ("scarlet-ui", "SCARLET_UI_SOURCE")):
        config += f'{variable} = {{ value = {json.dumps(str(checkouts[name]))}, force = true }}\n'
    config += '\n[target.aarch64-unknown-scarlet]\n'
    config += 'rustflags = ["--cfg", \'getrandom_backend="custom"\']\n'
    # Only test fixture paths and target flags are generated. Dependencies
    # resolve directly from their manifests and upstream lockfiles.
    write_generated(ROOT / ".cargo/config.toml", config)
    write_generated(PROJECT / ".scarlet/userspace.toml", config)
    return checkouts


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--published", action="store_true",
                        help="compatibility option; upstream commit pins are always used")
    parser.add_argument("--path", choices=list(pins()),
                        help="print one resolved source directory without preparing Cargo")
    args = parser.parse_args()
    if args.path:
        print(source(args.path))
    else:
        for name, path in prepare().items():
            print(f"{name}: {path}")


if __name__ == "__main__":
    main()
