[package]
name = "aarch64-switch-l4t-project"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "scarlet"
path = "src/main.rs"

[dependencies]
scarlet_modules = { package = "scarlet-modules", path = "../.scarlet/scarlet-modules" }
fdt = "0.1.5"
font8x8 = { version = "0.3", default-features = false, features = ["unicode"] }

[profile.release]
opt-level = 3
debug = 1
