[package]
name = "sgfx-backend-scarlet-maxwell"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"

[features]
default = ["std"]
std = ["dep:scarlet-os", "gpu-raw/std"]
scarlet-std = ["std"]

[dependencies]
maxwell-program-wire = { path = "../../shared/maxwell-program-wire" }
sgfx-shader-maxwell = { path = "../sgfx-shader-maxwell" }
maxwell-image-layout = { path = "../../shared/maxwell-image-layout" }
maxwell-submit-wire = { path = "../../shared/maxwell-submit-wire" }
gpu-raw = { git = "https://github.com/petitstrawberry/Scarlet", rev = "d3b1c05127d4df3616f988b81a99f616e8a88064", package = "gpu-raw", default-features = false }
scarlet-os = { git = "https://github.com/petitstrawberry/Scarlet", rev = "d3b1c05127d4df3616f988b81a99f616e8a88064", package = "scarlet-os", default-features = false, features = ["std"], optional = true }
sgfx-codegen-maxwell = { path = "../sgfx-codegen-maxwell" }
sgfx-core = { git = "https://github.com/petitstrawberry/sgfx", rev = "040dbb5cf42b75489504e1765183d37f6131f54c", default-features = false }

[lib]
name = "sgfx_backend_scarlet_maxwell"
path = "src/lib.rs"
