[package]
name = "sgfx-backend-scarlet-maxwell"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"

[features]
default = ["scarlet-std"]
std = ["dep:scarlet-os", "gpu-raw/std"]
scarlet-std = ["dep:scarlet-std", "gpu-raw/scarlet-std"]

[dependencies]
maxwell-submit-wire = { path = "../../shared/maxwell-submit-wire" }
gpu-raw = { git = "https://github.com/petitstrawberry/Scarlet", rev = "54bfdf3048a100fc4bfba5198e59bdb184702871", package = "gpu-raw", default-features = false }
scarlet-os = { git = "https://github.com/petitstrawberry/Scarlet", rev = "54bfdf3048a100fc4bfba5198e59bdb184702871", package = "scarlet-os", default-features = false, features = ["std"], optional = true }
scarlet-std = { git = "https://github.com/petitstrawberry/Scarlet", rev = "54bfdf3048a100fc4bfba5198e59bdb184702871", package = "scarlet-std", optional = true }
sgfx-codegen-maxwell = { path = "../sgfx-codegen-maxwell" }
sgfx-core = { git = "https://github.com/petitstrawberry/sgfx", rev = "0213c76bdc9777ddb2a3a25e30b54ac8c5e01912", default-features = false }

[lib]
name = "sgfx_backend_scarlet_maxwell"
path = "src/lib.rs"
