[package]
name = "input-qa"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
scarlet-os = { git = "https://github.com/petitstrawberry/Scarlet", rev = "e027956300006bd8a41c42691c6925c63039fd43", default-features = false, features = ["std"] }
sws-client = { git = "https://github.com/petitstrawberry/Scarlet", rev = "e027956300006bd8a41c42691c6925c63039fd43", default-features = false, features = ["std"] }
sws-protocol = { git = "https://github.com/petitstrawberry/Scarlet", rev = "e027956300006bd8a41c42691c6925c63039fd43", default-features = false, features = ["std"] }
scarlet-ui = { git = "https://github.com/petitstrawberry/scarlet-ui", rev = "6ef3e3c4da42898e8077b3698f08a95f9f718b8c", features = ["platform-sws"] }
scarlet-ui-macros = { git = "https://github.com/petitstrawberry/scarlet-ui", rev = "6ef3e3c4da42898e8077b3698f08a95f9f718b8c" }

[profile.release]
panic = "abort"
